package com.aryaxzell.truedown.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// Brand Colors
val BrandPrimary = Color(0xFF2563EB)
val BrandAccent = Color(0xFF06B6D4)
val BrandTikTokCoral = Color(0xFFFE2C55)
val BrandTikTokCyan = Color(0xFF25F4EE)

// Gradient Brushes for Expressive Visuals
val BrandTikTokGradient = Brush.horizontalGradient(
    listOf(BrandTikTokCyan, BrandTikTokCoral)
)
val BrandHeroGradientLight = Brush.linearGradient(
    listOf(Color(0xFFEFF6FF), Color(0xFFE0F2FE), Color(0xFFF5F3FF))
)
val BrandHeroGradientDark = Brush.linearGradient(
    listOf(Color(0xFF0F172A), Color(0xFF1E293B), Color(0xFF172554))
)

// M3 Expressive Light Color Tokens
val LightPrimary = Color(0xFF2563EB)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E3A8A)
val LightSecondary = Color(0xFF0284C7)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0F2FE)
val LightOnSecondaryContainer = Color(0xFF0369A1)
val LightTertiary = Color(0xFF7C3AED)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEDE9FE)
val LightOnTertiaryContainer = Color(0xFF4C1D95)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF8FAFC)
val LightSurfaceContainer = Color(0xFFF1F5F9)
val LightSurfaceContainerHigh = Color(0xFFE2E8F0)
val LightSurfaceContainerHighest = Color(0xFFCBD5E1)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF991B1B)

// M3 Expressive Dark Color Tokens
val DarkPrimary = Color(0xFF60A5FA)
val DarkOnPrimary = Color(0xFF0B192C)
val DarkPrimaryContainer = Color(0xFF1E3A8A)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFF38BDF8)
val DarkOnSecondary = Color(0xFF082F49)
val DarkSecondaryContainer = Color(0xFF0369A1)
val DarkOnSecondaryContainer = Color(0xFFE0F2FE)
val DarkTertiary = Color(0xFFA78BFA)
val DarkOnTertiary = Color(0xFF2E1065)
val DarkTertiaryContainer = Color(0xFF5B21B6)
val DarkOnTertiaryContainer = Color(0xFFEDE9FE)
val DarkBackground = Color(0xFF090D16)
val DarkOnBackground = Color(0xFFF1F5F9)
val DarkSurface = Color(0xFF0F172A)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF1E293B)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkSurfaceContainerLowest = Color(0xFF060911)
val DarkSurfaceContainerLow = Color(0xFF0B1120)
val DarkSurfaceContainer = Color(0xFF0F172A)
val DarkSurfaceContainerHigh = Color(0xFF1E293B)
val DarkSurfaceContainerHighest = Color(0xFF334155)
val DarkOutline = Color(0xFF475569)
val DarkOutlineVariant = Color(0xFF334155)
val DarkError = Color(0xFFF87171)
val DarkOnError = Color(0xFF450A0A)
val DarkErrorContainer = Color(0xFF7F1D1D)
val DarkOnErrorContainer = Color(0xFFFEE2E2)
