package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val BrandBlue = Color(0xFF2563EB)
val BrandBlueDark = Color(0xFF1D4ED8)
val BrandBlueContainer = Color(0xFFDBEAFE)
val BrandBlueOnContainer = Color(0xFF1E3A8A)

// M3 Light Color Tokens
val LightPrimary = Color(0xFF2563EB)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF1E3A8A)
val LightSecondary = Color(0xFF475569)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE2E8F0)
val LightOnSecondaryContainer = Color(0xFF1E293B)
val LightTertiary = Color(0xFF0284C7)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFE0F2FE)
val LightOnTertiaryContainer = Color(0xFF0369A1)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFF8FAFC)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF64748B)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)

// M3 Dark Color Tokens
val DarkPrimary = Color(0xFF60A5FA)
val DarkOnPrimary = Color(0xFF0F172A)
val DarkPrimaryContainer = Color(0xFF1E3A8A)
val DarkOnPrimaryContainer = Color(0xFFDBEAFE)
val DarkSecondary = Color(0xFF94A3B8)
val DarkOnSecondary = Color(0xFF0F172A)
val DarkSecondaryContainer = Color(0xFF1E293B)
val DarkOnSecondaryContainer = Color(0xFFF1F5F9)
val DarkTertiary = Color(0xFF38BDF8)
val DarkOnTertiary = Color(0xFF082F49)
val DarkTertiaryContainer = Color(0xFF0369A1)
val DarkOnTertiaryContainer = Color(0xFFE0F2FE)
val DarkBackground = Color(0xFF0B1120)
val DarkOnBackground = Color(0xFFF8FAFC)
val DarkSurface = Color(0xFF0F172A)
val DarkOnSurface = Color(0xFFF8FAFC)
val DarkSurfaceVariant = Color(0xFF1E293B)
val DarkOnSurfaceVariant = Color(0xFF94A3B8)
val DarkOutline = Color(0xFF475569)
val DarkOutlineVariant = Color(0xFF334155)
